### ISSUE TITLE
prepare_TsinghuaDogs not working

### ISSUE THREAD

**Issue by Mo-Kanya** [QuocThangNguyen/deep-metric-learning-tsinghua-dogs#3]
Hi,

I'm interested in using your dataset. However, when prepare_TsinghuaDogs.py is unzipping the downloaded files, an exception occurs:

Archive:  data/TsinghuaDogs.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data/TsinghuaDogs.zip or
        data/TsinghuaDogs.zip.zip, and cannot find data/TsinghuaDogs.zip.ZIP, period.
22-Jun-08 17:47:02  root  INFO: Downloading https://cg.cs.tsinghua.edu.cn/ThuDogs/high-annotations.zip to data/TsinghuaDogs/high-annotations.zip

Could you please fix it or tell me the proper way to use it?

**Comment by QuocThangNguyen** [comment]
Hi @Mo-Kanya, sorry for late replying.
Have you solved this issue yet ?

**Comment by Mo-Kanya** [comment]
I've got a copy from my colleague. Not sure if the download script works though.
