### ISSUE TITLE
checkpoints folder is empty 

### ISSUE THREAD

**Issue by HripsimeS** [QuocThangNguyen/deep-metric-learning-tsinghua-dogs#4]
@QuocThangNguyen First of all, thanks for the great work on fine-grained classification. I would like to test the repository train and inference, but unfortunatly I could not find **proxynca-resnet50.pth** pre-trained model in checkpoints folder. Can you please let me know where I can find and dowload it. Look forward to hearing frolm you!

**Comment by HripsimeS** [comment]
Ok I found the link https://drive.google.com/file/d/1i8r-z123USWRUD7VHDOH4M6cO73nTUJr/view
I will close this issue :)

**Comment by QuocThangNguyen** [comment]
No problem @HripsimeS. I'm glad that this repo benefits you.
