### ISSUE TITLE
Tsinghua Dogs dataset preparation 

### ISSUE THREAD

**Issue by HripsimeS** [QuocThangNguyen/deep-metric-learning-tsinghua-dogs#5]
@QuocThangNguyen Hello. I am having a bit problem in running **prepare_TsinghuaDogs.py** script for dataset preparation and getting error **IndexError: list index out of range**. Just wanted to check with you if I am doing things correctly.

So in **data** folder I opened **TsinghuaDogs** where I opened the following folders 
**High-Annotations** 
**high-resolution** 
**TrainAndValList** 
**train** 
**val**

Is this a correct data directory structure before running a **prepare_TsinghuaDogs.py** ?

![image](https://user-images.githubusercontent.com/42246765/201041503-a7fdb8ba-db69-4173-88ab-33736e065cf5.png)

![image](https://user-images.githubusercontent.com/42246765/201049137-70a72fae-2d1b-447e-a0c6-627d6fa2aa5b.png)

**Comment by HripsimeS** [comment]
@QuocThangNguyen the issue is fixed by manually downloading all files and then modifying **prepare_TsinghuaDogs.py** where I removed all downloading and unzipping parts, then just used lines for preparing train and validation sets to split dataset.

**Comment by QuocThangNguyen** [comment]
Maybe there are some changes in the dataset since I last looked 2 years ago. Glat that you can fix it.
Feel free to ask if you have any questions @HripsimeS
